Numpy in Python::::
####
Numpy ia a python Library used for fast numerical computational. It provides arrays,math function and tools for data science



In [ ]:
import numpy as np

Creating a array


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


2D Array::

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
#### Example 1::
numbers = [1,2,3,4,5,6,7,8]
result =  []
for x in numbers:
  result.append(x+2)
print(result)
## Example 2::
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
result1 = arr+2
print(result1)

[3, 4, 5, 6, 7, 8, 9, 10]
[ 3  4  5  6  7  8  9 10]


In [ ]:
### Example 2::
import time
start = time.time()
lst = list(range(1000000))
lst2 = [x*2 for x in lst]
end = time.time()
print(end-start)

0.08308815956115723


In [ ]:
### Example 3::
import time
start = time.time()
lst = np.arange(100000)
lst2 = lst*2
end = time.time()
print(end-start) ### It is used for the fast numerical Problem Solving

0.032622337341308594


In [ ]:

import sys
import numpy as np
lst = list(range(100000))
print(sys.getsizeof(lst))
arr = np.arange(100000)
print(arr.nbytes)


800056
800000


Arrary Properties::

In [ ]:
### Types of the array properties :: such as .shape,,size .dtype,.ndim and the .zeros,.ones , .arange()
import numpy as np
arr = np.array([[1,2,3,9],[4,5,6,0]])
print(arr.shape) ### It show the shape of the array
print(arr.dtype) ### It show the data type of the array
print(arr.ndim) ### It show the dimension of the array
print(arr.size) ### It show the how many item  of the array are there is present
print(arr.itemsize) ### It show the size of the array


(2, 4)
int64
2
8
8


In [ ]:
#### The Other Remaining Properties in a array ::
import numpy as np
arr = np.zeros((3, 4)) ### it gives the 3*4 matrix all the values in the zeros
print(arr)
arr = np.ones((3, 4)) ### it gives all the values of 3*4 in the 1
print(arr)
arr1 = np.array([1,2,3])
arr = np.empty((3,3)) ### it gives the empty garbarge Value's
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323 4.0e-323]]


Mathmatical Operation


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.mean())
print(arr*2)
print(arr+2)

1
8
36
4.5
[ 2  4  6  8 10 12 14 16]
[ 3  4  5  6  7  8  9 10]


Reshaping In Python


In [ ]:
### Reshaping the matrix::
import numpy as np
arr = np.arange(1,13)
print(arr)
print(arr.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Boolean Filtering :::


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr>2)
print(arr[arr>2])


[False False  True  True  True  True  True  True]
[3 4 5 6 7 8]


In [ ]:
### Example 2 ::
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3],[5,7,9]])
for i in arr2:
  print(i)
### For 2d::
for i in arr:
  print(i)
  ### Using the nested for loop in it's
print("For the Seperated Inside Looping the Values")
for row in arr2:
  for value in row:
    print(value)

[1 2 3]
[5 7 9]
1
2
3
4
5
6
7
8
For the Seperated Inside Looping the Values
1
2
3
5
7
9


In [ ]:
### Example 3:: ### Scalrized method
import numpy as np
import time
arr = np.arange(1000000)
start = time.time()
for i in range(len(arr)):
  arr[i] = arr[i]*2
end = time.time()
print(end-start)
### For the Vectorized Method ::
### We don't used the for loop in the numpy ,pandas
arr = np.arange(1000000)
start = time.time()
arr = arr*2
end = time.time()
print(end-start)


0.3976156711578369
0.0016505718231201172


In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/instagram_users_lifestyle.csv")
df["is_premium"] = np.where(df["subscription_status"] == "Premium", "Yes", "NO")
df["is_bussiness"] = np.where(df["subscription_status"] == "Business", "Yes","No")
print(df.head(20))
print(df.tail(5))
### 1st how many row and columns;
### 2nd how many null Values ;
###

    user_id   app_name  age             gender         country urban_rural  \
0         1  Instagram   51             Female           India       Rural   
1         2  Instagram   64             Female  United Kingdom       Urban   
2         3  Instagram   41             Female          Canada       Urban   
3         4  Instagram   27         Non-binary     South Korea       Urban   
4         5  Instagram   55               Male           India       Urban   
5         6  Instagram   20               Male   United States       Rural   
6         7  Instagram   33         Non-binary           Japan       Urban   
7         8  Instagram   51             Female  United Kingdom       Urban   
8         9  Instagram   31             Female  United Kingdom       Urban   
9        10  Instagram   35               Male   United States       Urban   
10       11  Instagram   23               Male           India    Suburban   
11       12  Instagram   23               Male   United States  

In [ ]:
nums = [1,2,1]
print(nums)
output = nums*2
print(nums)

[1, 2, 1]
[1, 2, 1]


In [ ]:
words = ["abc","bcd","aaaa","cbc"]
x = "z"
ans = []
for i in range(len(words)):
  if x in words[i]:
    ans.append(words[i])
print(ans)

[]


Array Creation
1) Numpy Identity and Diagonal


In [ ]:
import numpy as np
arr = np.eye(3) ### it gives it identity Matrix
print(arr)
arr = np.diag((1,3)) ### It gives the diagonal which is given on a list
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0]
 [0 3]]


2. Range Based :::


In [ ]:
import numpy as np
### generating the range of the array ::
arr = np.arange(5,9) ### it work same as the range Property::
print(arr)
arr = np.arange(1,10,2)
print(arr)
#### Generating the linespace of the array::
arr = np.linspace(1,4,9) ### start = 1 , and stop = 9 and gap = 9-1 = 8 values is generating based on that line of the code
print(arr)
arr = np.linspace(1,2,3)
print(arr)

[5 6 7 8]
[1 3 5 7 9]
[1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625 4.   ]
[1.  1.5 2. ]


Stucture of the array


In [ ]:
# .reshape() it is used for the reshaping the array

# .flatten() it is used for the new copy

# .ravel() it is usef for the viewing the data structure

# .T it is used for the transporing the array
import numpy as np
arr = np.array([[1,2,5],[8,9,0]])
print(arr)
### Reshaping the Array
reshaping1 = arr.reshape(3,2)
print(reshaping1)
### New Copying the Values
copying2 = arr.flatten()
print(copying2)

### viewing the array values
viewing3 = arr.ravel()
print(viewing3)
### Transposew
result = arr.transpose() ### it transpose
result2 = arr.T
print(result2)
print(result)



[[1 2 5]
 [8 9 0]]
[[1 2]
 [5 8]
 [9 0]]
[1 2 5 8 9 0]
[1 2 5 8 9 0]
[[1 8]
 [2 9]
 [5 0]]
[[1 8]
 [2 9]
 [5 0]]
